### ISSUE TITLE
Urgent additions

### ISSUE THREAD

**Issue by Vendicated** [nearlySplat/splatsh#3]
- [X] We need to add a prettierrc to keep the formatting consistent
- [X] Tests should be added
- [X] pre commit hooks to format/lint and github workflow to lint should be created (I can do that)
- [X] enable strict null checks in ur tsconfig to avoid `cannot read property ... of undefined`
- [X] Add eslint to enforce good style
- [X] Add readme :DDDD 
- [x] Add LICENSE - I suggest GPLv3

**Comment by nearlySplat** [comment]
Will get working on README soon:tm:

**Comment by nearlySplat** [comment]
README has been done!

**Comment by nearlySplat** [comment]
Licence should be ticked off now.

**Comment by Vendicated** [comment]
All done!! 🎉
