### ISSUE TITLE
Sync stdin and add stderr support

### ISSUE THREAD

**Issue by nearlySplat** [nearlySplat/splatsh#6]
This is needed to support things like Vim, Nano and even prompt-based programs.

**Comment by Vendicated** [comment]
how would we even do this

**Comment by nearlySplat** [comment]
Remember the `occupied` variable? Yup, this is its big moment.

**Comment by Vendicated** [comment]
what exactly do you mean by stderr support? isn't this already done via the printfErr

**Comment by nearlySplat** [comment]
Currently, only (std)`out` is supported by `CommandResult`. Don't worry, I'm nearly finished on it, and you'll see once I push.
